README.md

add general information about the project

readme info

---

.prettierrc
src/main.jsx

For keep consistancy in our codebase, @itsnotpolza suggest to add empty line in every file which we have.
Now, I think, it will work, but every Windows user should reinstall our project (delete locally and pull repo again) to avoid undesired behaviour of commiting changes in the future.

feat: add eol property to Prettier config

---

src/Components/ErrorBoundary/ErrorBoundary.jsx
src/Components/ErrorBoundary/index.js
src/Components/index.js
src/main.jsx

right now text with alert error on the top because we don't have style on the body element. actually, it's centered

feat: add errorBoundary component

---

.eslintrc.json
package-lock.json
package.json
src/components/ErrorBoundary/ErrorBoundary.jsx
src/i18n/i18n.js
src/main.jsx
src/pages/App.jsx
src/pages/Categories.jsx
src/pages/Landing.jsx

This article was pretty helpful to setup import sorting for our project.
https://dev.to/julioxavierr/sorting-your-imports-with-eslint-3ped

feat: add & config eslint-plugin-simple-import-sort

---

.github/workflows/main.yml

It triggered the workflow on pull request events not targeted on the main branch before

fix: change branches in workflow

---

src/components/AddWallet/AddWallet.jsx
src/i18n/i18n_en.json

https://user-images.githubusercontent.com/39521158/180176541-9653de34-b0be-4ea4-a3b5-f58b403ff880.mov
https://user-images.githubusercontent.com/39521158/180177810-1f2bbbfa-623f-4f49-84d5-d704ade34e05.mov

feat: add validation to wallet form

---

src/components/LoginForm/LoginForm.jsx

feat: login fields validation

---

static.json

ci: add heroku static buildpack url rewriting configuration

---

src/components/Header/Navbar.jsx
src/i18n/i18n_en.json
src/pages/App.jsx
src/pages/Expenses.jsx

feat: create expenses page

---

src/components/LoginForm/LoginForm.jsx
src/pages/Login.jsx

feat: add theme switcher to login page + apply color modes

---

src/components/AddWalletModal/AddWalletModal.jsx

Just putting UI components to the right place: in previous variant ModalFooter was in ModalBody.
Current PR fix that.

refactor: addWalletModal

---

src/pages/Expenses.jsx

Added layout for applied filters tags

Filters tags layout

---

.env.dist
src/api/ApiProvider.js
src/api/Wallet.js
src/components/AddWalletModal/AddWalletModal.jsx
src/i18n/i18n_en.json

Add screenshots with the changes applied here. 
https://user-images.githubusercontent.com/44428466/181482845-acc9a18e-9be2-4838-856c-5342bec142db.mp4

feat: connect wallet creation to BE

---

src/components/ColorModeToggle/ColorModeToggle.jsx
src/components/Header/Header.jsx
src/components/Header/Logo.jsx
src/components/Header/NavDrawer.jsx
src/components/Header/Navbar.jsx
src/components/Header/Notification.jsx
src/components/Header/UserMenu.jsx
src/components/Header/UserName.jsx
src/i18n/i18n_en.json
src/pages/Expenses.jsx
src/theme/theme.js

Fix margin top:
Desktop:
Tablet:
Fix margin top:
Desktop:
Tablet:

style: add responsive-header, add globalstyles, fix margin expenses

---

src/api/getCurrency.js
src/components/AddWalletModal/AddWalletModal.jsx

adding a list of currencies from the backend
https://user-images.githubusercontent.com/83176493/182406192-c4fe35d3-d20d-4ac5-9c95-b73974baddd3.mp4

feat: add connect currency

---

src/components/Header/Header.jsx
src/components/Header/Logo.jsx
src/components/Header/NavDrawer.jsx
src/components/Header/Navbar.jsx
src/components/Layout.jsx

fixed warning in NavBar Breadcrumb 

fix: fixed warning

---

src/components/FiltersExpenses/FiltersExpenses.jsx

Made filters' layout responsive
https://user-images.githubusercontent.com/47990337/182671946-bbf9be2b-2971-454a-8c31-0e7062680aaf.mov

refactor: made filters' layout responsive

---

src/pages/WalletView.jsx

https://user-images.githubusercontent.com/47990337/182693494-610d6f2e-aa8c-45e8-b542-f7291fd78a85.mov

fix: fix wallewView page

---

src/components/Layout.jsx
src/index.css
src/pages/Expenses.jsx

style: bind footer to the bottom

---

src/components/AccordionComponent/AccordionComponent.jsx
src/components/AccordionHeadings/AccordionHeadings.jsx
src/components/ColorModeToggle/ColorModeToggle.jsx
src/components/ExpenseItem/ExpenseItem.jsx
src/components/FiltersExpenses/FiltersExpenses.jsx
src/components/Header/Header.jsx
src/components/Header/Logo.jsx
src/components/Header/NavDrawer.jsx
src/components/Header/Navbar.jsx
src/components/Header/Notification.jsx
src/components/Header/UserMenu.jsx
src/components/Header/UserName.jsx
src/components/IncomeItem/IncomeItem.jsx
src/components/LoginForm/LoginForm.jsx
src/components/WalletCard/WalletCard.jsx
src/components/WalletsList/WalletsList.jsx
src/pages/Categories.jsx
src/pages/Expenses.jsx
src/pages/Incomes.jsx
src/pages/Login.jsx
src/theme/theme.js

Add useCentralTheme, drawer close after page selection
https://user-images.githubusercontent.com/80061297/183018259-a830e7ed-1ba2-4e29-ae84-369e3fa03901.mp4
https://user-images.githubusercontent.com/80061297/183036392-e46e285e-5dbc-4ea5-aa60-e7d1ba6b20ec.mp4

style: fix color, drower closing, change margins

---

src/api/Currency.js
src/api/getCurrency.js
src/components/AddWalletModal/AddWalletModal.jsx
src/pages/Categories.jsx
src/pages/Landing.jsx
src/pages/Login.jsx
src/pages/WalletView.jsx

https://user-images.githubusercontent.com/47990337/183109724-567e39fe-b74e-45ed-83ea-4ba9bf3820da.mov

fix: add checks for received data

---

src/api/Category.js
src/api/Currency.js
src/api/DefaultCategories.js
src/api/Notification.js
src/api/Transactions.js
src/api/Wallet.js

fix: update api paths

---

src/api/ApiProvider.js
src/api/AuthProvider.js
src/api/Transactions.js
src/api/Wallet.js
src/components/AddIncomeModal/AddIncomeModal.jsx
src/components/Header/Header.jsx
src/i18n/i18n_en.json
src/pages/Landing.jsx

https://user-images.githubusercontent.com/47990337/183465554-3e5975a9-02a2-46b4-9d59-cca004f3ed94.mov

feat: connect api to createIncome

---

src/api/Category.js
src/api/DeleteAccount.js
src/api/Wallet.js

- [] Bugfix
- [ x] Commit messages follow [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)
changed code only
changed code only

Refactoring  userID in requests 

---

src/api/ApiProvider.js
src/api/Authorisation.js
src/components/LoginForm/LoginForm.jsx
src/components/WalletsList/WalletsList.jsx
src/i18n/i18n_en.json

connect log in to the backend 

feat: connect log in to the backend

---

src/components/WalletCard/WalletCard.jsx
src/components/WalletCarousel/WalletCarousel.jsx
src/components/WalletsList/WalletsList.jsx
src/pages/WalletView.jsx

Fixed walletView page, fixed carousel with wallets, fixed 'Default' wallet badge
https://user-images.githubusercontent.com/47990337/183990156-2a213fb2-1789-46fd-8b6f-fe8dcbeb6d0d.mov
https://user-images.githubusercontent.com/47990337/183990213-97b73db4-fc11-448d-b95b-83cb7f65768e.mov

fix: fix walletView page and carousel

---

src/components/TransactionList/TransactionList.jsx
src/i18n/i18n_en.json

header for transaction list with explain each column 
- [x
] Console has been checked for warnings

feat: add headers for transaction list

---

src/components/AccordionHeadings/AccordionHeadings.jsx
src/components/AddCategoryModal/AddCategoryModal.jsx
src/pages/Categories.jsx

https://user-images.githubusercontent.com/65466953/183913657-8da1d7f6-cdaa-4e9c-96fe-0e4891b6db4a.mp4

fix: add category and income buttons

---

src/api/DefaultCategory.js
src/components/AddIncomeModal/AddIncomeModal.jsx
src/components/EditExpenseModal/EditExpenseModal.jsx
src/pages/Incomes.jsx
src/pages/Landing.jsx

fix: remove defaultCategories, fix incomes

---

src/components/ExpenseItem/ExpenseItem.jsx
src/components/IncomeItem/IncomeItem.jsx
src/pages/Expenses.jsx
src/pages/Incomes.jsx
src/pages/Landing.jsx

Feat: add currency to expenses and incomes

---

src/components/AddExpenseModal/AddExpenseModal.jsx
src/components/AddIncomeModal/AddIncomeModal.jsx
src/components/AddWalletModal/AddWalletModal.jsx
src/components/EditExpenseModal/EditExpenseModal.jsx
src/components/Selector/SelectControlled.jsx
src/components/Selector/index.js
src/i18n/i18n_en.json

change <Selector> to the chakra-reacr-select
- [] Synced up with latest from the main branch/Code is linted
- [x
https://user-images.githubusercontent.com/83176493/184382589-820bfcd4-7247-4b5b-acf9-cb1ba40739ce.mp4
[x] Chakra components/constants/hooks have been used wherever possible

feat: Change Select to chakra react select

---

src/components/ColorModeToggle/ColorModeToggle.jsx
src/components/Header/Header.jsx
src/components/Header/Logo.jsx
src/components/Header/NotificationsMenu.jsx
src/components/LoginForm/LoginForm.jsx
src/components/TransactionItem/TransactionItem.jsx
src/components/WalletsList/WalletsList.jsx
src/i18n/i18n_en.json
src/pages/Login.jsx

https://user-images.githubusercontent.com/47990337/184473079-6522b173-8070-4b40-89be-31241ca015ba.mov

fix: fix layout and small bugs

---

src/components/Footer/Footer.jsx

Deleted absolute position at footer

fix: fix filter layout

---

src/pages/Categories.jsx

Add scroll to categories expenses and inciomes
https://user-images.githubusercontent.com/80061297/184555856-2c432ba6-0c40-4d97-81f4-7f8559420413.mp4

style: add scroll in categories page

---

src/components/AddIncomeModal/AddIncomeModal.jsx

fix: deleted IsRecurring from incomes

---

src/components/TransactionItem/TransactionItem.jsx

fix: fix transaction item note and subcategory

---

src/api/Transaction.js
src/pages/Expenses.jsx

- add 'Add expense' button 
- add pagination to list ("Show more")
https://user-images.githubusercontent.com/39521158/184847852-18f3b2f5-8a9e-4dd2-84b1-6ed43a2bcaa1.mov

feat: add pagination & button add expenses

---

src/helpers/helpers.js

fix: fix list of recent transactions

---

src/components/AddWalletModal/AddWalletModal.jsx
src/helpers/helpers.js

- [] Console has been checked for warnings
https://user-images.githubusercontent.com/94010184/184857818-48d3d3eb-1436-4219-a0e2-07f197004218.mp4

Connect "Set wallet default" to BE

---

src/components/Header/Header.jsx
src/hooks/index.js
src/hooks/useAutoLogout.jsx

Logout user automatically if app is inactive for 1 hour.
On video you can see autoLogout happens much faster than should => setTimeout were changed to 3 sec for demo purposes. In PR that time is set to 1 hour.
https://user-images.githubusercontent.com/68731150/184864844-e41a04cd-3456-4185-aa7c-5b50a15372fc.mov

feat: add autologout

---

src/components/FiltersExpenses/FiltersExpenses.jsx

refactor: fix filter date button on Expense page

---

src/components/EditCategoryModal/EditCategoryModal.jsx
src/i18n/i18n_en.json

This is a fix from my 123 commit, the back has corrected his validation and now you can only change the color in the category
https://user-images.githubusercontent.com/80061297/184868012-10bc8ed0-d987-42e6-a23d-103e51c3dfd6.mp4
https://user-images.githubusercontent.com/80061297/184867889-11c720ba-0c09-4f0d-90c9-2b455f84c861.mp4

fix: validation name

---

src/pages/Incomes.jsx

add income button to income page

feat: add income button

---

src/api/User.js
src/components/Header/NotificationsMenu.jsx

fix: add date to notifications, fix endpoint

---

src/components/Header/Header.jsx
src/components/Header/Navbar.jsx
src/components/Header/UserMenu.jsx

Change the settings icon for user avatar icon with user's initials parsed from user's fullname in BE for more user friendly

Loading header

---

src/api/Category.js
src/components/AccordionComponent/AccordionComponent.jsx
src/i18n/i18n_en.json
src/pages/Categories.jsx

**Delete** Income and Expense Category
[INC.CAT](http://inc.cat/)-03
[INC.CAT](http://inc.cat/)-05
https://user-images.githubusercontent.com/80061297/185226508-84818be1-38f9-457e-a160-5be018ceb784.mp4

feat: delete category

---

src/pages/Expenses.jsx
src/pages/Incomes.jsx
src/pages/Landing.jsx
src/pages/WalletView.jsx

fix: fix get data request

---

src/components/AddCategoryModal/AddCategoryModal.jsx
src/components/Header/UserMenu.jsx

changes alert messages to toast messages according to US requirements

Change alerts messages

---

src/components/AddCategoryModal/AddCategoryModal.jsx
src/components/AddExpenseModal/AddExpenseModal.jsx
src/components/AddIncomeModal/AddIncomeModal.jsx
src/components/AddPayerModal/AddPayerModal.jsx
src/components/AddSubCategoryModal/AddSubCategoryModal.jsx
src/components/AddWalletModal/AddWalletModal.jsx
src/components/ConfirmationModal/ConfirmationModal.jsx
src/components/EditCategoryModal/EditCategoryModal.jsx
src/components/EditExpenseModal/EditExpenseModal.jsx
src/components/EditIncomeModal/EditIncomeModal.jsx
src/components/EditWalletModal/EditWalletModal.jsx
src/components/NotificationModal/NotificationModal.jsx

https://user-images.githubusercontent.com/68731150/185755887-d58c34dd-e6ae-40ea-be33-1f95d116b4fb.mov
https://user-images.githubusercontent.com/68731150/185755981-cc0b1242-2815-420f-b4e0-a4bf54967fc9.mov

feat: add scroll to all modals

---

src/components/FiltersReport/FiltersReport.jsx
src/components/Header/NavDrawer.jsx
src/pages/Report.jsx

fix: fix report page bugs

---

src/components/TransactionList/TransactionList.jsx

fix error "dataPayers is not iterable"
https://user-images.githubusercontent.com/39521158/185868665-def63ff0-7829-4ae4-9f80-03306550e6d8.mov
https://user-images.githubusercontent.com/39521158/185869431-9c67d9e6-5a36-4e5e-83aa-20a434c16730.mov

fix: fix default value of payersData 

---

src/components/AddCategoryModal/AddCategoryModal.jsx

fix: fix color in colorPicker

---

src/components/AccordionComponent/AccordionComponent.jsx

https://user-images.githubusercontent.com/44428466/185815791-4cef5294-9db7-4b01-a797-812582962601.mp4

fix: fix categories color hover effect

---

src/components/AccordionComponent/AccordionComponent.jsx
src/components/AddCategoryModal/AddCategoryModal.jsx
src/pages/Categories.jsx

Deleted accordion from income categories
Added mutation for adding new categories
Added sorting for categories by name
https://user-images.githubusercontent.com/47990337/185965416-f2497f9e-71cd-4c0a-97d4-a3da4699471a.mov

fix: fix categories page

---

src/helpers/helpers.js
src/pages/Statistics.jsx

fix: add currency symbol to reports

---

src/api/Transaction.js
src/components/FiltersExpenses/CalendarPicker.jsx
src/components/FiltersExpenses/utils.js
src/components/FiltersIncomes/FiltersIncomes.jsx
src/components/FiltersIncomes/index.js
src/components/TransactionList/TransactionList.jsx
src/components/index.js
src/i18n/i18n_en.json
src/pages/Incomes.jsx

Сonnect filters for incomes  with backend

Сonnect filter for incomes  with backend

---

src/components/EditExpenseModal/EditExpenseModal.jsx
src/components/EditIncomeModal/EditIncomeModal.jsx

add X the same behavior as a cancel button
https://user-images.githubusercontent.com/39521158/186074011-047c74a7-6dc8-429b-9739-0ed8750b241e.mov
https://user-images.githubusercontent.com/39521158/186074185-378ff59a-78da-4b3f-8915-7e6dd410ff43.mov

fix: add X the same behavior as cancel button

---

src/components/AddPayerModal/AddPayerModal.jsx
src/components/AddSubCategoryModal/AddSubCategoryModal.jsx
src/components/EditCategoryModal/EditCategoryModal.jsx

Fix  remove scroll behavior

---

src/components/SubCategoryList/SubCategoryList.jsx

https://user-images.githubusercontent.com/44428466/186176015-19123dc5-5c36-4eef-8a78-f5a90157fcd2.mp4

fix: fix subcategory color hover effect

---

src/api/SubCategory.js
src/components/AccordionComponent/AccordionComponent.jsx
src/components/AddCategoryModal/AddCategoryModal.jsx
src/components/AddSubCategoryModal/AddSubCategoryModal.jsx
src/components/SubCategoryList/SubCategoryList.jsx

sub categories are refetched
add feat  delete subcategories
remove edit icon
https://user-images.githubusercontent.com/39521158/186184341-5e367fa1-0c45-41c0-84e3-656a00e4a741.mov
https://user-images.githubusercontent.com/39521158/186184000-d7ae3550-e703-45b6-971a-ca941e3f8da2.mov

feat: delete subcategories 

---

src/components/LoginForm/LoginForm.jsx
src/components/TransactionList/TransactionList.jsx
src/pages/Expenses.jsx
src/pages/Incomes.jsx

add sorting by amount depending on selected wallet 
and also i removed border on the logo of the  login page which Polina does not like so much))
https://user-images.githubusercontent.com/83176493/186190196-58addb9f-bea1-4ef4-a739-ddd4f9fb2a6b.mp4
https://user-images.githubusercontent.com/83176493/186190203-7d50ea68-12c4-4f1a-a256-15230afc37a1.mp4

fix: add sort by amount

---

src/components/ColorModeToggle/ColorModeToggle.jsx
src/components/Header/Header.jsx
src/components/Header/Logo.jsx
src/components/Header/NavDrawer.jsx
src/components/Header/Navbar.jsx
src/components/Header/NotificationsMenu.jsx
src/components/Header/UserMenu.jsx
src/components/Header/UserName.jsx
src/theme/theme.js

- put `/home` into Logo and remove it from main nav
- other style changes
https://user-images.githubusercontent.com/68731150/186230542-85a8dda2-0fb9-46f2-a0fe-4111ad290fd3.mov
https://user-images.githubusercontent.com/68731150/186230576-2c93fc3b-d6d9-4dfd-8c45-c52d2e6f9b80.mov
https://user-images.githubusercontent.com/68731150/186230412-5e690262-a062-4b28-85a0-345cee0a5e83.mov
https://user-images.githubusercontent.com/68731150/186230481-329887d3-3891-4426-b1b5-bda3f5a5a9c6.mov

refactor: massive Header restyle

---

src/components/WalletCarousel/WalletCarousel.jsx

https://user-images.githubusercontent.com/65466953/186282527-eed43ba9-ca2d-4039-a2fa-30cc76c9bd49.mp4
https://user-images.githubusercontent.com/65466953/186282550-4399be63-5c7a-41eb-b511-59c365db37cb.mp4

Fix carousel

---

src/components/FiltersReport/FiltersReport.jsx
src/components/Header/NotificationsMenu.jsx
src/components/SelectControlled/SelectControlled.jsx
src/pages/Statistics.jsx

fix: fix zIndex

---

src/components/LoginForm/LoginForm.jsx

A minor change of how login form looks => more consistent with the entire app interface.

refactor: restyle login form

---

src/components/AddWalletModal/AddWalletModal.jsx
src/components/SelectControlled/SelectControlled.jsx

feat: add wallet validation

---

src/components/TransactionList/TransactionList.jsx
src/pages/App.jsx
src/pages/Landing.jsx
src/pages/WalletView.jsx

Reverts Yulatun/sandbox-exadel-2022#183

Revert "Add preloaders"

---

src/components/AccordionComponent/AccordionComponent.jsx

fix: fix toast

---

src/components/SelectControlled/SelectControlled.jsx

fix: fix validation

---

src/components/Header/NotificationsMenu.jsx
src/theme/theme.js

https://user-images.githubusercontent.com/44428466/186496033-779713a6-c59c-4f2c-ae12-c8a9b731074e.mp4
https://user-images.githubusercontent.com/44428466/186496086-959177a5-ff35-4d12-96c1-8d942376b332.mp4

refactor: make notifications more readable
